#Robocode Compiler Properties
#Mon Apr 13 13:25:22 JST 2026
compiler.binary=
compiler.classpath=-classpath libs\\robocode.jar;"C\:\\Users\\qtaro\\source\\repos\\ai-java-student-materials\\Assignments\\P2 - Robocode\\env\\robots"
compiler.options=
robocode.version=1.10.0
