#Robocode window sizes
#Mon Apr 13 18:28:56 JST 2026
net.sf.robocode.ui.dialog.ConsoleDialog=518,279,500,400
net.sf.robocode.ui.dialog.NewBattleDialog=38,25,850,650
net.sf.robocode.ui.dialog.PreferencesDialog=107,203,712,294
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
net.sf.robocode.ui.dialog.TeamCreator=460,239,616,482
net.sf.robocode.ui.editor.RobocodeEditor=386,174,764,611
